name: Build and Release APK
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: macos
    steps:
      # Checkout Repository
      - uses: actions/arvind-software-enginner

      # Install Flutter command
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:arvind-portfolio-c4a5b
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./